const T={
uk:{home:"Головна",features:"Можливості",new:"Що нового",download:"Завантаження",available:"Версія 6.2.1 доступна",hero1:"Більше контролю.",hero2:"Більше швидкості.",heroText:"Windows Optimizer Ultra об'єднує очищення, моніторинг, Repair Center, Ultimate Performance та системні інструменти.",downloadExe:"Завантажити EXE",more:"Дізнатися більше",version:"Версія",langs:"Мов",tools:"Інструментів",optimized:"Оптимізовано для",interface:"Інтерфейс",diagnostics:"Діагностика",monitoring:"Моніторинг",featuresTitle:"Все потрібне для Windows в одному місці",featuresText:"Продуктивність, діагностика, очищення та системні інструменти.",cleaning:"Очищення",systemTools:"Системні інструменти",network:"Мережа",f1:"Створення, пошук GUID та активація плану максимальної продуктивності.",f2:"SFC, DISM CheckHealth, ScanHealth, RestoreHealth та CHKDSK Scan.",f3:"TEMP, DNS, кошик, кеш ескізів, Disk Cleanup і Storage Sense.",f4:"CPU, RAM, диски та процеси в реальному часі.",f5:"Device Manager, Event Viewer, Resource Monitor, Services та інше.",f6:"Network Info, DNS cleanup та тест підключення.",n1:"Повна перевірка коду",n1t:"Прибрано дублікати методів та перевірено синтаксис.",n2:"Покращена діагностика",n2t:"System Scan, Network Test, Installed Apps і Advanced Report.",n3:"PRO Design",n3t:"Нові картки, адаптивний дизайн і 5 мов.",optimizerDesc:"Оптимізація, Repair Center, моніторинг та системні інструменти.",cleanerDesc:"Компактний інструмент для швидкого очищення Windows.",downloadCleaner:"Завантажити Win Cleaner",admin:"Деякі функції можуть запитувати права адміністратора Windows.",faqTitle:"Часті запитання",q1:"Для якої Windows програма?",a1:"Основна версія орієнтована на Windows 11 64-bit.",q2:"Навіщо права адміністратора?",a2:"Вони потрібні лише для системних операцій.",q3:"Як працює завантаження?",a3:"Поклади EXE-файли поруч із index.html у корені GitHub Pages."},
en:{home:"Home",features:"Features",new:"What's new",download:"Downloads",available:"Version 6.2.1 is available",hero1:"More control.",hero2:"More speed.",heroText:"Windows Optimizer Ultra combines cleaning, monitoring, Repair Center, Ultimate Performance and system tools.",downloadExe:"Download EXE",more:"Learn more",version:"Version",langs:"Languages",tools:"Tools",optimized:"Optimized for",interface:"Interface",diagnostics:"Diagnostics",monitoring:"Monitoring",featuresTitle:"Everything Windows needs in one place",featuresText:"Performance, diagnostics, cleaning and system tools.",cleaning:"Cleaning",systemTools:"System tools",network:"Network",f1:"Create the plan, find its GUID and activate Ultimate Performance.",f2:"SFC, DISM CheckHealth, ScanHealth, RestoreHealth and CHKDSK Scan.",f3:"TEMP, DNS, Recycle Bin, thumbnail cache, Disk Cleanup and Storage Sense.",f4:"Real-time CPU, RAM, disk and process information.",f5:"Device Manager, Event Viewer, Resource Monitor, Services and more.",f6:"Network Info, DNS cleanup and connectivity test.",n1:"Full code review",n1t:"Duplicate methods removed and syntax checked.",n2:"Improved diagnostics",n2t:"System Scan, Network Test, Installed Apps and Advanced Report.",n3:"PRO Design",n3t:"New cards, responsive design and 5 languages.",optimizerDesc:"Optimization, Repair Center, monitoring and system tools.",cleanerDesc:"Compact utility for quick Windows cleaning.",downloadCleaner:"Download Win Cleaner",admin:"Some features may request Windows administrator permission.",faqTitle:"Frequently asked questions",q1:"Which Windows version?",a1:"The main build targets Windows 11 64-bit.",q2:"Why administrator rights?",a2:"They are required only for system operations.",q3:"How does downloading work?",a3:"Put the EXE files next to index.html in the GitHub Pages root."},
pl:{home:"Główna",features:"Funkcje",new:"Co nowego",download:"Pobieranie",available:"Wersja 6.2.1 jest dostępna",hero1:"Więcej kontroli.",hero2:"Więcej szybkości.",heroText:"Windows Optimizer Ultra łączy czyszczenie, monitoring, Repair Center, Ultimate Performance i narzędzia systemowe.",downloadExe:"Pobierz EXE",more:"Więcej informacji",version:"Wersja",langs:"Języków",tools:"Narzędzi",optimized:"Zoptymalizowano dla",interface:"Interfejs",diagnostics:"Diagnostyka",monitoring:"Monitoring",featuresTitle:"Wszystko dla Windows w jednym miejscu",featuresText:"Wydajność, diagnostyka, czyszczenie i narzędzia systemowe.",cleaning:"Czyszczenie",systemTools:"Narzędzia systemowe",network:"Sieć",f1:"Tworzenie planu, wyszukiwanie GUID i aktywacja Ultimate Performance.",f2:"SFC, DISM CheckHealth, ScanHealth, RestoreHealth i CHKDSK Scan.",f3:"TEMP, DNS, kosz, pamięć miniaturek, Disk Cleanup i Storage Sense.",f4:"CPU, RAM, dyski i procesy w czasie rzeczywistym.",f5:"Menedżer urządzeń, Podgląd zdarzeń, Monitor zasobów, Usługi i więcej.",f6:"Informacje sieciowe, czyszczenie DNS i test połączenia.",n1:"Pełna kontrola kodu",n1t:"Usunięto duplikaty metod i sprawdzono składnię.",n2:"Lepsza diagnostyka",n2t:"System Scan, Network Test, Installed Apps i Advanced Report.",n3:"PRO Design",n3t:"Nowe karty, responsywny design i 5 języków.",optimizerDesc:"Optymalizacja, Repair Center, monitoring i narzędzia systemowe.",cleanerDesc:"Kompaktowe narzędzie do szybkiego czyszczenia Windows.",downloadCleaner:"Pobierz Win Cleaner",admin:"Niektóre funkcje mogą wymagać uprawnień administratora.",faqTitle:"Najczęstsze pytania",q1:"Dla jakiego Windows?",a1:"Główna wersja jest dla Windows 11 64-bit.",q2:"Po co administrator?",a2:"Tylko do operacji systemowych.",q3:"Jak działa pobieranie?",a3:"Umieść pliki EXE obok index.html w katalogu głównym GitHub Pages."},
de:{home:"Start",features:"Funktionen",new:"Neuigkeiten",download:"Downloads",available:"Version 6.2.1 ist verfügbar",hero1:"Mehr Kontrolle.",hero2:"Mehr Geschwindigkeit.",heroText:"Windows Optimizer Ultra vereint Bereinigung, Überwachung, Repair Center, Ultimate Performance und Systemwerkzeuge.",downloadExe:"EXE herunterladen",more:"Mehr erfahren",version:"Version",langs:"Sprachen",tools:"Werkzeuge",optimized:"Optimiert für",interface:"Oberfläche",diagnostics:"Diagnose",monitoring:"Überwachung",featuresTitle:"Alles für Windows an einem Ort",featuresText:"Leistung, Diagnose, Bereinigung und Systemwerkzeuge.",cleaning:"Bereinigung",systemTools:"Systemwerkzeuge",network:"Netzwerk",f1:"Plan erstellen, GUID finden und Ultimate Performance aktivieren.",f2:"SFC, DISM CheckHealth, ScanHealth, RestoreHealth und CHKDSK Scan.",f3:"TEMP, DNS, Papierkorb, Miniaturcache, Disk Cleanup und Storage Sense.",f4:"CPU, RAM, Datenträger und Prozesse in Echtzeit.",f5:"Geräte-Manager, Ereignisanzeige, Ressourcenmonitor, Dienste und mehr.",f6:"Netzwerkinformationen, DNS-Bereinigung und Verbindungstest.",n1:"Vollständige Codeprüfung",n1t:"Doppelte Methoden entfernt und Syntax geprüft.",n2:"Bessere Diagnose",n2t:"System Scan, Network Test, Installed Apps und Advanced Report.",n3:"PRO Design",n3t:"Neue Karten, responsives Design und 5 Sprachen.",optimizerDesc:"Optimierung, Repair Center, Überwachung und Systemwerkzeuge.",cleanerDesc:"Kompaktes Werkzeug zur schnellen Windows-Bereinigung.",downloadCleaner:"Win Cleaner herunterladen",admin:"Einige Funktionen können Administratorrechte anfordern.",faqTitle:"Häufige Fragen",q1:"Welche Windows-Version?",a1:"Die Hauptversion ist für Windows 11 64-Bit.",q2:"Warum Administratorrechte?",a2:"Nur für Systemvorgänge.",q3:"Wie funktioniert der Download?",a3:"Lege die EXE-Dateien neben index.html im GitHub-Pages-Stammverzeichnis."},
es:{home:"Inicio",features:"Funciones",new:"Novedades",download:"Descargas",available:"La versión 6.2.1 está disponible",hero1:"Más control.",hero2:"Más velocidad.",heroText:"Windows Optimizer Ultra reúne limpieza, monitorización, Repair Center, Ultimate Performance y herramientas del sistema.",downloadExe:"Descargar EXE",more:"Más información",version:"Versión",langs:"Idiomas",tools:"Herramientas",optimized:"Optimizado para",interface:"Interfaz",diagnostics:"Diagnóstico",monitoring:"Monitorización",featuresTitle:"Todo para Windows en un solo lugar",featuresText:"Rendimiento, diagnóstico, limpieza y herramientas del sistema.",cleaning:"Limpieza",systemTools:"Herramientas del sistema",network:"Red",f1:"Crea el plan, encuentra el GUID y activa Ultimate Performance.",f2:"SFC, DISM CheckHealth, ScanHealth, RestoreHealth y CHKDSK Scan.",f3:"TEMP, DNS, papelera, caché de miniaturas, Disk Cleanup y Storage Sense.",f4:"CPU, RAM, discos y procesos en tiempo real.",f5:"Administrador de dispositivos, Visor de eventos, Monitor de recursos, Servicios y más.",f6:"Información de red, limpieza DNS y prueba de conexión.",n1:"Revisión completa del código",n1t:"Se eliminaron métodos duplicados y se comprobó la sintaxis.",n2:"Mejor diagnóstico",n2t:"System Scan, Network Test, Installed Apps y Advanced Report.",n3:"PRO Design",n3t:"Nuevas tarjetas, diseño adaptable y 5 idiomas.",optimizerDesc:"Optimización, Repair Center, monitorización y herramientas del sistema.",cleanerDesc:"Herramienta compacta para limpiar Windows rápidamente.",downloadCleaner:"Descargar Win Cleaner",admin:"Algunas funciones pueden solicitar permisos de administrador.",faqTitle:"Preguntas frecuentes",q1:"¿Para qué Windows?",a1:"La versión principal está pensada para Windows 11 de 64 bits.",q2:"¿Por qué permisos de administrador?",a2:"Solo para operaciones del sistema.",q3:"¿Cómo funciona la descarga?",a3:"Coloca los archivos EXE junto a index.html en la raíz de GitHub Pages."}
};

function setLang(lang){
  const l=T[lang]?lang:"uk";
  document.documentElement.lang=l;
  document.querySelectorAll("[data-i18n]").forEach(el=>{
    const v=T[l][el.dataset.i18n];
    if(v) el.textContent=v;
  });
  localStorage.setItem("optimizerLang",l);
}
const sel=document.getElementById("language");
if(sel){const saved=localStorage.getItem("optimizerLang")||"uk";sel.value=saved;setLang(saved);sel.addEventListener("change",e=>setLang(e.target.value));}

document.querySelectorAll('a[href^="#"]').forEach(a=>a.addEventListener("click",e=>{const t=document.querySelector(a.getAttribute("href"));if(t){e.preventDefault();t.scrollIntoView({behavior:"smooth"});}}));

const obs=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add("visible");obs.unobserve(e.target);}}),{threshold:.1});
document.querySelectorAll(".reveal").forEach(el=>obs.observe(el));

document.querySelectorAll(".faq details").forEach(d=>d.addEventListener("toggle",()=>{if(d.open)document.querySelectorAll(".faq details").forEach(o=>{if(o!==d)o.open=false;});}));

console.log("%c Windows Optimizer Site 3.0 ","background:#176fff;color:white;padding:8px 12px;border-radius:8px;font-weight:bold;");
